---

- name: download file
  raw: '(New-Object -TypeName System.Net.WebClient).DownloadFile("{{ dot_net_452.url }}", "{{ dot_net_452_download_location }}\\{{ dot_net_452.file }}")'
  changed_when: False
  check_mode: no
  register: download_dot_net_file
  until: download_dot_net_file is success
  delay: 3
  retries: 5

- name: install .NET 4.5.2
  raw: '{{ dot_net_452_download_location }}\{{ dot_net_452.file }} /q /norestart'
  changed_when: True
  check_mode: no
  ignore_errors: yes

- name: remove dotnet file
  raw: 'Remove-Item -Path {{ dot_net_452_download_location }}\{{ dot_net_452.file }} -Force'
  changed_when: False
  check_mode: no
  ignore_errors: yes